version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2022-07-06T20-29-49Z
    volumes:
      - /lwb/proj/minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /lwb/proj/minio/data --console-address="0.0.0.0:9001"